name: UNet_illu_bilateralFilter
use_tb_logger: true
model_type: UNetIlluBilateralFilterModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
#### datasets

mask_ratio: 0.5
datasets:
  train:
    name: LOL
    type: PairedImageUNetBilateralFilterDataset
    dataroot_gt: 
    dataroot_lq: 
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 120
    use_flip: true
    use_rot: true
    win_size: 20
    percent: 0.5

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 0
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: LOL
    type: PairedImageUNetBilateralFilterDataset
    dataroot_gt: 
    dataroot_lq: 
    io_backend:
      type: disk
    percent: 0.5
    win_size_test: 20


#### network structures
network_g:
  type: UNet_BilateralFilter_mask
  in_channels: 1
  channels: 6
  out_channels: 1



#### path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

#### training settings: learning rate scheme, loss

train:
  ema_decay: 0.999
  mask_ratio: 0.5
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000, 250000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up
  dual: False

  # losses
  forward:
    type: MaskL1loss
    win_size: 20
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 2000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 3000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~